FROM python:3.10

WORKDIR /app

RUN apt-get install libgomp1
RUN pip install poetry

COPY poetry.lock .
COPY pyproject.toml .

RUN poetry config virtualenvs.create false
RUN poetry install --without train --with inference

COPY src/ src/
COPY settings.toml .
COPY model.txt .

CMD [ "python", "src/app.py" ]