version: '3.7'

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - benchmarking

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - 8000:8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8000/health" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    networks:
      - benchmarking
    depends_on:
      - jaeger

  fiber:
    build:
      context: .
      dockerfile: Dockerfile.fiber
    ports:
      - 3000:3000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:3000/health" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    networks:
      - benchmarking
    depends_on:
      - jaeger

networks:
  benchmarking: